### PR TITLE
Add a symbol version script

### PR DESCRIPTION
**Pull request by simo5**
This should work as is, but I am not sure about the version number there, please check the version script.

Here some info about it:
https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html

### CODE REVIEW

**Comment by npmccallum** [comment]
I think you forgot to git add libjose.map.

**Comment by simo5** [comment]
Added

**Comment by npmccallum** [comment]
Can you please make the tests pass?

**Comment by simo5** [comment]
They pass for me on f26, what doesn't work ?

**Comment by simo5** [comment]
Uhm I think I know, let's see if this rebase works now

**Pull request merged**
