### PR TITLE
Add a strict mode to jose_jwk_allowed()

### LINKED ISSUE #9: Make jose_jwk_allowed() have a strict mode
Currently, jose_jwk_allowed() returns true if the JWK contains none of the appropriate attributes. A strict mode would fail in this case.

### PR DESCRIPTION
**Pull request by npmccallum**
When req == true, the JWK absolutely MUST have the right op or use.

Fixes #9

### CODE REVIEW

**Comment by simo5** [comment]
LGTM,
what about adding a test that confirms all assignments permutations ?

**Comment by npmccallum** [comment]
@simo5 I added tests. I also ensured that we deny when there is a conflict between use and key_ops.

**Comment by simo5** [comment]
ACK

**Comment by npmccallum** [comment]
Merged.

**Pull request closed without merging**
