### PR TITLE
Correct jose_jws.3 man page example

### PR DESCRIPTION
**Pull request by grooverdan**
Make the ver function in the example have the jws variable used within the function.

### CODE REVIEW

**Review by sarroutbi — COMMENTED** [review]
If this is changed ... should not the code be changed consequently?

I mean, change include/jose/jws.h similarly

**Comment by grooverdan** [comment]
Ok. Didn't see that there too so yes, obviously should change also. Is the change right however?

**Comment by sarroutbi** [comment]
> Ok. Didn't see that there too so yes, obviously should change also. Is the change right however?

Yes, IMHO, change LGTM

**Comment by sarroutbi** [comment]
Hello @grooverdan. May I ask you change include/jose/jws.h similarly?

**Comment by grooverdan** [comment]
Apologizes for the delay, there now.

**Review by sarroutbi — APPROVED** [review]
Changes LGTM. Thanks for the PR

**Pull request merged**
