### PR TITLE
Enable copr builds and add packit config

### PR DESCRIPTION
**Pull request by dhodovsk**
Let us introduce [packit service](https://packit.dev) to you - the automation to integrate upstream open source projects into Fedora operating system.

After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.

But there is more. By using packit, you can for example enable adding new releases into Fedora Rawhide.

What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!

For more info, please:
 * check out the documentation: https://packit.dev/docs/
 * contact @packit-service

The spec you see in this PR was fetched from your package's Fedora dist-git.

### CODE REVIEW

**Comment by simo5** [comment]
Won't thi spec file always create the same NVR for each PR ?
I would expect some git id ortimestamp to be embedded in the .spec file to have unique packages?
Or does packit do some magic here?

**Comment by dhodovsk** [comment]
The source value in the specfile would be temporarily replaced by values with the built source, for example:
```
--- a/jose.spec
+++ b/jose.spec
@@ -1,11 +1,11 @@
 Name:           jose
-Version:        10
-Release:        5%{?dist}
+Version:        v10.11.g76d9f17
+Release:        1%{?dist}
 Summary:        Tools for JSON Object Signing and Encryption (JOSE)
 
 License:        ASL 2.0
 URL:            https://github.com/latchset/%{name}
-Source0:        https://github.com/latchset/%{name}/releases/download/v%{version}/%{name}-%{version}.tar.bz2
+Source0:        jose-v10.11.g76d9f17.tar.bz2
 
 BuildRequires:  gcc
 BuildRequires:  pkgconfig
@@ -44,7 +44,7 @@ Obsoletes:      lib%{name}-zlib-devel < %{version}-%{release}
 This package contains development files for lib%{name}.
 
 %prep
-%setup -q
+%setup -q -n jose-v10.11.g76d9f17
 
 %build
 %if 0%{?rhel}
@@ -79,6 +79,9 @@ make %{?_smp_mflags} check
 %{_mandir}/man3/jose*.3*
 
 %changelog
+* Tue Nov 12 2019 Dominika Hodovska <dhodovsk@redhat.com> - v10.11.g76d9f17-1
+- Development snapshot (76d9f177)
```

This modified spec file would then be used for the copr build.

**Comment by simo5** [comment]
@dhodovsk you say "would" but I guess you mean "will"? Ie that is how it actually works today, not how it could work?
One more question, how does it know what is the actual basic version to use in the version string? Is that configured somewhere? Does it take it from the original spec file?
I am trying to figure out if maintenance is needed on any file to keep the rpm version numbers up to date.

**Comment by simo5** [comment]
@dhodovsk ok so I fixed the build with centos in another PR, could you please trim away the changelog from the spec file (not terribly intersting for us to have the fedaora package changelog) and rebase on top of current master?
If tests pass I will then approve and push

**Comment by TomasTomecek** [comment]
Dominika asked me to comment here.

The version is being picked up from git using `git describe`:

https://github.com/packit-service/packit/blob/1e8d239f2bfed5f8864c2e5a66143e4d8598ef9d/packit/config/package_config.py#L92

This is the default behaviour and obviously you can override it with your custom scripts, makefiles, etc. This is documented on our website: https://packit.dev/docs/actions/

**Comment by simo5** [comment]
@TomasTomecek sounds reasonable, any chance you or dominika can update the PR so we can try to merge it ?

**Comment by TomasTomecek** [comment]
@simo5: @dhodovsk got sidetracked with some other work, we'll try to figure it out by the end of the week.

Thanks for bearing with us!

**Comment by dhodovsk** [comment]
Sorry for the late response, the branch is now rebased and changelog trimmed.

**Pull request merged**
