### PR TITLE
Meson Changes

### PR DESCRIPTION
**Pull request by tcyrus**
I made these build fixes as part of an attempt to use `libjose` as a meson subproject

- headers are in `include/jose` instead of `jose` (install path is still the same)
- replaced manual link paths with `include_directories`
- removed `PATH` modification from `jose-fmt` and `jose-jwk-use` tests (already done in `tests/meson.build`)
- declared a meson dependency for `libjose` (internal and subproject usage)

### CODE REVIEW

**Comment by simo5** [comment]
I've too k a quick look, what prompted the need to change jose -> include/jose ?
Nothing against it, but why?

**Comment by tcyrus** [comment]
> I've took a quick look, what prompted the need to change `jose` -> `include/jose`?
> Nothing against it, but why?

I removed the manual linking flags

```
add_project_arguments(
  '-I' + meson.current_source_dir(),
  '-I' + meson.current_build_dir(),
#  ...
```

and replaced it with `include_directories`, which required the directory layout change.

This was done to get subproject builds working.

I was able to get tang to build using jose as a subproject ([branch](https://github.com/tcyrus/tang/tree/meson-changes))

**Comment by simo5** [comment]
@tcyrus I rerun as some builds seemed stuck or with dependency install errors, can you check if any are now failing due to code vs infra? I'll try to take another look tomorrow as well.

**Comment by sergio-correia** [comment]
@tcyrus: could you rebase your branch on top of the latest changes fixing the CI, please?

**Comment by tcyrus** [comment]
Done

**Comment by simo5** [comment]
LGTM, the only failing tests are on fedora:rawhide and ubuntu:devel which are known fails in CI right now.

**Review by sergio-correia — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
