### PR TITLE
Implement JWK Thumbprints

### LINKED ISSUE #5: Implement JWK Thumbprints
https://tools.ietf.org/html/rfc7638

### PR DESCRIPTION
**Pull request by npmccallum**
This includes three new API functions, a new jose command and a new
hook for implementing hash algorithms.

Fixes #5

### CODE REVIEW

**Comment by npmccallum** [comment]
@simo5 can you review this?

**Comment by simo5** [comment]
I could, but I was almost done doing an implementation myself ...

**Comment by simo5** [comment]
Note, you should probably clone bake jose into your github account and create branches there.

Besides that ACK

**Comment by npmccallum** [comment]
I planned to start doing that. I was just getting this off of my hard drive.

One flaw in my current approach is that I don't allow octet arrays as input to PBES2, only password strings. I'm toying with the idea of requiring b64 strings instead. This would allow both while carefully distinguishing between a cryptographically strong JWK and a cryptographically weak PBES2 input.

**Pull request merged**
