### PR TITLE
https://github.com/latchset/jose/issues/46 Poor error feedback

### PR DESCRIPTION
**Pull request by oleshii**
I tryed to resolve this challenge. Currently I am ready to be critisized with the clever guys.

### CODE REVIEW

**Comment by sarroutbi** [comment]
Could you please merge jose master branch into PR branch to apply Github Actions CI steps?

**Comment by sarroutbi** [comment]
Closing this. New PR #105 created to fix #46 issue

**Comment by oleshii** [comment]
Hi Sergio,
you may use my implementation if you like. I do not mind.
Regards,
Oleg

**Comment by sarroutbi** [comment]
Hello @oleshii.

There are some details in that implementation that could be improved, IMHO. That is why I decided to create a new one.

Basically, the main issue had to do with definitions of algorithms. They can not be defined again in an array for them to be checked. Some functions already exist to check if an algorithm exists, so they must be leveraged for this check. Otherwise, the information is spread in different parts, making the code harder to maintain.

**Pull request closed without merging**
