### PR TITLE
Add sphinx documentation of jose

### PR DESCRIPTION
**Pull request by tiran**
Jose lacks API documentation. I started sphinx documentation with breathe and doxygen for C API.

Signed-off-by: Christian Heimes christian@python.org

### CODE REVIEW

**Comment by npmccallum** [comment]
This looks great! Before I merge, can you add optional doc building/install to autoconf/automake?

**Comment by tiran** [comment]
I'm not an AM expert but my Google Fu was strong enough to figure it out.

**Comment by npmccallum** [comment]
We need more than this. Let me define what I'm looking for. We should look for our documentation requirements during configure. If they are found, we should build the documentation.

Additionally, there should be a switch to configure to force on the documentation requirements. See, for instance, --with-openssl.

Finally, this needs to be added to the test suite via the --with-* flags. This will reveal in Travis CI which platforms can't build the docs.

**Comment by tiran** [comment]
Check for

* ```doxygen``` command
* either
  * ```sphinx-build-2``` command
  * ```python2 -c "import breathe"```
* or
  * ```sphinx-build-3``` command
  * ```python3 -c "import breathe"```
* run ```make -C docs html SPHINXBUILD=sphinx-build-[23]```

**Comment by npmccallum** [comment]
Can you rebase this?

**Comment by tiran** [comment]
Done

**Comment by npmccallum** [comment]
Will you be integrating this into the build system as I requested?

**Comment by tiran** [comment]
Is it really worth the extra effort? I'm going to hook up our documentation with readthedocs to get it automatically build.

**Comment by simo5** [comment]
@tiran, do you think you'll update this PR to work on current master ?

**Comment by sarroutbi** [comment]
@tiran: any update on this? Are you planning to resolve conflicting files?

**Comment by sarroutbi** [comment]
It is been since this PR has no activity. Closing it. Please, feel free to reopen it in case you consider necessary

**Pull request closed without merging**
